name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest

      - name: Lint with flake8
        run: flake8 usd_mcp_server

      - name: Check formatting with black
        run: black --check usd_mcp_server

      - name: Syntax check
        run: python -m compileall usd_mcp_server

      - name: Run tests
        run: pytest 